# Stocks_site/azure-pipelines.yml
trigger:
  - main

variables:
  - group: sonar-vars
  - name: acrName
    value: pratibaacr123450
  - name: aksCluster
    value: pratiba-aks-cluster
  - name: resourceGroup
    value: rg-pratiba-platform-dev
  - name: imageName
    value: stocks-app
  - name: tag
    value: $(Build.BuildId)
  -name: poolImage
    value: selfhosted-linux

stages:

- template: templates/stages/build-test-sonar-python.yml@templates
  parameters:
    poolImage: $(poolImage)
    sonarEnabled: true
    sonarProjectKey: 'stocks-project'
    sonarHostUrl: 'http://20.127.146.185:9000'
    sonarToken: '$(SONAR_TOKEN)'

- template: templates/stages/sca.yml@templates
  parameters:
    poolImage: $(poolImage)
    failOnVuln: false

- template: templates/stages/docker.yml@templates
  parameters:
    poolImage: $(poolImage)
    acrName: $(acrName)
    imageName: $(imageName)
    tag: $(tag)

- stage: Deploy
  displayName: "Deploy to AKS"
  jobs:
    - job: DeployJob
      pool:
        name: $(poolImage)

      steps:
        - checkout: self

        - template: templates/steps/aks-deploy.yml@templates
          parameters:
            aksCluster: $(aksCluster)
            resourceGroup: $(resourceGroup)
            acrName: $(acrName)
            imageName: $(imageName)
            tag: $(tag)
            helmRelease: 'stocks-release'
            chartPath: 'stocks-chart'