# Stocks_site/Demo/stocks-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: stocks-app
  template:
    metadata:
      labels:
        app: stocks-app
    spec:
      containers:
        - name: stocks-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}