# Stocks_site/Demo/stocks-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: stocks-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: stocks-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}